// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1Gd1rGV-LgP0OYZBNsuJyZxTX8J3CDU',
    appId: '1:177685089319:web:4f8fbc2746a4223ef5d202',
    messagingSenderId: '177685089319',
    projectId: 'flutter-crud-7f304',
    authDomain: 'flutter-crud-7f304.firebaseapp.com',
    storageBucket: 'flutter-crud-7f304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-7F99I6m2C-aTpddn7U72wiy3gZoiZg8',
    appId: '1:177685089319:android:21798c78798f6d20f5d202',
    messagingSenderId: '177685089319',
    projectId: 'flutter-crud-7f304',
    storageBucket: 'flutter-crud-7f304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjg5ESbE95JLlthyPq084n1HbZdXzzJo',
    appId: '1:177685089319:ios:912f1e3fc3853685f5d202',
    messagingSenderId: '177685089319',
    projectId: 'flutter-crud-7f304',
    storageBucket: 'flutter-crud-7f304.appspot.com',
    iosClientId: '177685089319-eedet08vs241rh2q0sn48o862v4uumue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjg5ESbE95JLlthyPq084n1HbZdXzzJo',
    appId: '1:177685089319:ios:1bf8dc731144a809f5d202',
    messagingSenderId: '177685089319',
    projectId: 'flutter-crud-7f304',
    storageBucket: 'flutter-crud-7f304.appspot.com',
    iosClientId: '177685089319-1hckrohv66pd8234toeskerk3lvau914.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase.RunnerTests',
  );
}
